sudo: false
language: node_js
node_js: '5'
addons:
  postgresql: '9.4'
before_script:
- bash install.sh
script:
- source env.sh && npm run test
notifications:
  slack: devops-training-spb:kfjTXFxdFQxyBbAJ0UtYVqOe
deploy:
  app: limitless-sierra-82649
  provider: heroku
  api_key:
    secure: b/2C5ximT24x3tBzCHWDwARxbspmuoAJWP9rtqflW9of2ZfhBSoQmgLaYpCbqWgobhSGYiupu1ee2HwHfDiTHJbUHQIA9Lu1OWct5Cklr37TPeBcE/+vhdok6A58E1Wk3iy3HyfZYoZFi0H8pZt5muqGKZbuca4+/l+u8QC/reLJsbXVEiwDktmuXUcVRLri5kVkW5EaWkb8n207snCykh7aJeZSsWUojpO/J1f7e6Ryz16tBM0OU5V2fkf5ZHjGJ1J3NVm6ezRxwbtiZ7hyMaUSyLx7757LDfwF9J92lukgDZAa5C5XKS0OM0+7gML8LILfB65gPQSZfIugQ2NI2S7f3d/ndXo+umEjYODqM90heXEIplrnS7f8mD1JBIiViLWmDvb9ai1arC82pOkJvU0OY32rhtZZly//sVsXqgZM/mJwEGqU2UwCfzQrmWrQ8xnplaTCyDTzgwZ8MffnvyKz8NaPETquWN2e1dkn129UCvYT9jnEysWBxzo748+v4Wamv3z/36DoTA8c/uqn4rAYAewD4tk15h4VsW0NoL7pJ07ptR354vzIo89D22PoG9n/EtVYh/RtfJMbUODoz4tsLfkTmjQuZrKmUa78khjDMhDM4SpdEpjBKhZlva3+9EY7LpY14ZgwygihDH529PFxnZilYsIWXiuvUkh8J0A=
